server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-data-2-db
    username: postgres
    password: 1
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        show_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
