server:
    port: 9080

# Details for our datasource
spring:
    datasource:
        url: jdbc:postgresql://localhost:55000/waa-lab3
        username: postgres
        password: postgrespw

# Hibernate properties
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect        
        hibernate:
            ddl-auto: create-drop
            # naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                format-sql: true
                show-sql: true
        defer-datasource-initialization: true
    sql:
        init.mode: always